# Nombre del Workflow que verás en la pestaña "Actions"
name: (MANUAL) Build y Deploy Unity WebGL a itch.io

#
# Esto activa el botón de "Run workflow"
#
on:
  workflow_dispatch:

jobs:
  # ------ 1. TRABAJO DE COMPILACIÓN (BUILD) ------
  build:
    name: 🏗️ Build Unity (WebGL)
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Caché para acelerar builds (opcional pero recomendado)
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**/*', 'Packages/**/*', 'ProjectSettings/**/*') }}
          restore-keys: |
            Library-

      # 3. Compila el proyecto con GameCI
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          # Usa los secretos que guardamos en el Paso 2
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "Mango Studio Game"
          targetPlatform: WebGL
          # Carpeta donde se guardará la build
          buildsPath: build/webgl
          
      # 4. Guarda la build para que el siguiente 'job' pueda usarla
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgl-build
          path: build/webgl

  # ------ 2. TRABAJO DE DESPLIEGUE (DEPLOY) ------
  deploy:
    name: 🚀 Deploy to itch.io
    needs: build # Se espera a que termine el 'job' de 'build'
    runs-on: ubuntu-latest
    
    steps:
      # 1. Descarga la build compilada
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: build/webgl

      # 2. Sube la build a itch.io usando Butler
      - name: Deploy to itch.io
        uses: yeslayla/butler-publish-itchio-action@v1
        with:
          api_key: ${{ secrets.ITCHIO_API_KEY }}
          
          # ¡CAMBIA ESTO! Formato: "tu-usuario-de-itchio/el-nombre-de-tu-juego"
          game: "mangostudiourjc/catpuccino" 
          
          # ¡CAMBIA ESTO! El canal al que subes (ej: "web-testing" o "web-latest")
          channel: "web-testing" 
          
          # La carpeta que contiene la build WebGL
          package: build/webgl